name: instagram_clone
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#-------------- PACKAGES --------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  readmore: ^3.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.5

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.0

#-------------- ./ PACKAGES END --------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

    #-------------- LOCAL ASSETS --------------#
  assets:
    - assets/logos/
    - assets/posts/
    - assets/profile/

  #-------------- LOCAL FONTS --------------#
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
